import SwiftUI

struct LinkWhatsAppView: View {
    @Environment(\.dismiss)
    private var dismiss

    var body: some View {
        NavigationStack {
            VStack(spacing: 22) {

                Image(
                    systemName: "qrcode"
                )
                .font(
                    .system(size: 110)
                )

                Text(
                    "Link WhatsApp"
                )
                .font(.title2.bold())

                Text(
                    "A QR code generated by the server will appear here. Scan it from WhatsApp → Linked Devices."
                )
                .multilineTextAlignment(
                    .center
                )
                .foregroundStyle(
                    .secondary
                )

                ProgressView(
                    "Preparing connection…"
                )
            }
            .padding(30)
            .navigationTitle(
                "New Account"
            )
            .navigationBarTitleDisplayMode(
                .inline
            )
            .toolbar {
                ToolbarItem(
                    placement:
                        .cancellationAction
                ) {
                    Button("Close") {
                        dismiss()
                    }
                }
            }
        }
    }
}
